console.log("Iniciando server clínica de pilotagem.... carregando chalk");
let halk = require('chalk');
console.log(halk.blue("carregando express"));
let express = require('express');
console.log(halk.blue("carregando config"));
let config = require('./config');
console.log(halk.blue("Criando instância com express"));
const app = express();
let routes = require('./routes');
app.use('/', routes);
console.log(halk.blue("Configurando a porta de escuta do serviço"));
app.listen(config.port);
console.log(halk.blue("Serviço OK, aguardando requisição"));